### ISSUE TITLE
Non-PHP backdoor

### ISSUE THREAD

**Issue by melvinsh** [bartblaze/PHP-backdoors#1]
This does not look like PHP to me: https://github.com/bartblaze/PHP-backdoors/blob/master/Deobfuscated/file.php

**Comment by scriptzteam** [comment]
Somehow it seems like a fake gif look at the header "GIF89a;", not php backdoor anway...

**Comment by bartblaze** [comment]
Some PHP backdoors indeed add a GIF header to fool AV, but in this case it's no PHP backdoor anyways. Thank you, removed.
